@startuml
title
    Keyple 2.0 - Calypso Card Extension - 2.0.0 (02/04/2021)
end title

' == THEME ==

'Couleurs issues de : https://htmlcolorcodes.com/fr/tableau-de-couleur/tableau-de-couleur-design-plat/
!define C_GREY1 F8F9F9
!define C_GREY2 F2F3F4
!define C_GREY3 E5E7E9
!define C_GREY4 D7DBDD
!define C_GREY5 CACFD2
!define C_GREY6 BDC3C7
!define C_LINK 3498DB
!define C_USE 27AE60

skinparam Shadowing false
skinparam ClassFontStyle italic
skinparam ClassBorderColor #D4AC0D
skinparam stereotypeABorderColor #A9DCDF
skinparam stereotypeIBorderColor #B4A7E5
skinparam stereotypeCBorderColor #ADD1B2
skinparam stereotypeEBorderColor #EB93DF
' Red
skinparam ClassBackgroundColor<<red>> #FDEDEC
skinparam ClassBorderColor<<red>> #E74C3C
hide <<red>> stereotype
' Purple
skinparam ClassBackgroundColor<<purple>> #F4ECF7
skinparam ClassBorderColor<<purple>> #8E44AD
hide <<purple>> stereotype
' blue
skinparam ClassBackgroundColor<<blue>> #EBF5FB
skinparam ClassBorderColor<<blue>> #3498DB
hide <<blue>> stereotype
' Green
skinparam ClassBackgroundColor<<green>> #E9F7EF
skinparam ClassBorderColor<<green>> #27AE60
hide <<green>> stereotype
' Grey
skinparam ClassBackgroundColor<<grey>> #EAECEE
skinparam ClassBorderColor<<grey>> #2C3E50
hide <<grey>> stereotype

' == CONTENT ==

legend top
    __Colors legend__ :
    * __External API references__ :
    ** <back:yellow>**Service API**</back>
    ** <back:cyan>**Commons API**</back>
end legend

package "org.eclipse.keyple.card.calypso" as calypso {
    +class "**final** CalypsoCardExtensionProvider" as CalypsoCardExtensionProvider {
        +{static} CalypsoCardExtension getService ()
    }
    +interface "<<<back:cyan>KeypleCardExtension</back>>>\nCalypsoCardExtension" as CalypsoCardExtension {
        --
        +PoCardSelection createPoCardSelection (<back:yellow>CardSelector</back> poCardSelector, boolean acceptInvalidatedPo)
        ..
        +SamCardResourceProfileExtension createSamCardResourceProfileExtension ()
        +PoTransactionService createPoSecuredTransaction (<back:yellow>Reader</back> reader, PoSmartCard poSmartCard, PoSecuritySetting poSecuritySetting)
        ..
        +PoTransactionService createPoUnsecuredTransaction (<back:yellow>Reader</back> reader, PoSmartCard poSmartCard)
    }
    package po {
        +interface "<<<back:yellow>CardSelection</back>>>\nPoCardSelection" as PoCardSelection {
            --
            ...
        }
        +enum SelectFileControl {
            --
            ...
        }
        +interface "<<<back:yellow>SmartCard</back>>>\nPoSmartCard" as PoSmartCard {
            --
            ...
        }
        +interface DirectoryHeader {
            --
            ...
        }
        +interface ElementaryFile {
            --
            ...
        }
        +interface FileHeader {
            --
            ...
        }
        +interface FileData {
            --
            ...
        }
        +enum PoRevision {
            --
            ...
        }
        +interface SvLoadLogRecord {
            --
            ...
        }
        +interface SvDebitLogRecord {
            --
            ...
        }
    }
    package sam {
        +interface "<<<back:cyan>KeypleCardResourceProfileExtension</back>>>\nSamCardResourceProfileExtension" as SamCardResourceProfileExtension {
            +SamCardResourceProfileExtension setSamRevision (SamRevision samRevision)
            +SamCardResourceProfileExtension setSamSerialNumberRegex (String samSerialNumberRegex)
            +SamCardResourceProfileExtension setSamUnlockData (String samUnlockData)
        }
        +interface "<<<back:yellow>SmartCard</back>>>\nSamSmartCard" as SamSmartCard {
            --
            ...
        }
        +enum SamRevision {
            --
            ...
        }
    }
    package transaction {
        +interface PoTransactionService {
            --
            ...
        }
        +class "**final** PoSecuritySetting" as PoSecuritySetting {
            --
            +{static} Builder builder (String samCardResourceProfileName)
            ..
            ...
        }
        +class "**final** Builder" as PoSecuritySettingBuilder {
            --
            ...
            +PoSecuritySetting build ()
        }
    }
}

' Associations

CalypsoCardExtensionProvider ..> CalypsoCardExtension #C_USE : provide >

CalypsoCardExtension .up.> SamCardResourceProfileExtension #C_USE : create >
CalypsoCardExtension ..> PoSecuritySetting #C_USE : use >
CalypsoCardExtension ..> PoCardSelection #C_USE : create >
CalypsoCardExtension ..> PoSmartCard #C_USE : use >
CalypsoCardExtension ..> PoTransactionService #C_USE : create >

PoTransactionService ..> PoSecuritySetting #C_USE : use >
PoTransactionService ..> SelectFileControl #C_USE : use >

PoSecuritySetting ..> PoSecuritySettingBuilder #C_USE : provide >

PoSecuritySettingBuilder .up.> PoSecuritySetting #C_USE : create >

SamCardResourceProfileExtension ..> SamRevision #C_USE : use >

SamSmartCard ..> SamRevision #C_USE : provide >

PoCardSelection ..> SelectFileControl #C_USE : use >

PoSmartCard ..> DirectoryHeader #C_USE : provide >
PoSmartCard ..> ElementaryFile #C_USE : provide >
PoSmartCard ..> FileHeader #C_USE : provide >
PoSmartCard ..> FileData #C_USE : provide >
PoSmartCard ..> PoRevision #C_USE : provide >
PoSmartCard ..> SvLoadLogRecord #C_USE : provide >
PoSmartCard ..> SvDebitLogRecord #C_USE : provide >

' == LAYOUT ==

'PoRevision -[hidden]- SamCardResourceServiceBuilder

' == STYLE ==

package calypso #C_GREY1 {}
package po #C_GREY2 {}
package sam #C_GREY2 {}
package transaction #C_GREY2 {}


@enduml