@startuml
title
    Keyple 2.0 - Calypso Card Extension - 2.0.0 (21/05/2021)
end title

' == THEME ==

'Couleurs issues de : https://htmlcolorcodes.com/fr/tableau-de-couleur/tableau-de-couleur-design-plat/
!define C_GREY1 F8F9F9
!define C_GREY2 F2F3F4
!define C_GREY3 E5E7E9
!define C_GREY4 D7DBDD
!define C_GREY5 CACFD2
!define C_GREY6 BDC3C7
!define C_LINK 3498DB
!define C_USE 27AE60

skinparam Shadowing false
skinparam ClassFontStyle italic
skinparam ClassBorderColor #D4AC0D
skinparam stereotypeABorderColor #A9DCDF
skinparam stereotypeIBorderColor #B4A7E5
skinparam stereotypeCBorderColor #ADD1B2
skinparam stereotypeEBorderColor #EB93DF
' Red
skinparam ClassBackgroundColor<<red>> #FDEDEC
skinparam ClassBorderColor<<red>> #E74C3C
hide <<red>> stereotype
' Purple
skinparam ClassBackgroundColor<<purple>> #F4ECF7
skinparam ClassBorderColor<<purple>> #8E44AD
hide <<purple>> stereotype
' blue
skinparam ClassBackgroundColor<<blue>> #EBF5FB
skinparam ClassBorderColor<<blue>> #3498DB
hide <<blue>> stereotype
' Green
skinparam ClassBackgroundColor<<green>> #E9F7EF
skinparam ClassBorderColor<<green>> #27AE60
hide <<green>> stereotype
' Grey
skinparam ClassBackgroundColor<<grey>> #EAECEE
skinparam ClassBorderColor<<grey>> #2C3E50
hide <<grey>> stereotype

' == CONTENT ==

legend top
    __Colors legend__ :
    * __External API references__ :
    ** <back:yellow>**calypsonet-java-reader-api**</back>
    ** <back:cyan>**keyple-java-commons-api**</back>
end legend

package "org.eclipse.keyple.card.calypso" as calypso {
    +interface "<<<back:cyan>KeypleCardExtension</back>>>\nCalypsoExtensionService" as CalypsoExtensionService {
        --
        +{static} CalypsoExtensionService getInstance ()
        ..
        +CalypsoSelector createCardSelector ()
        +CalypsoCardSelection createCardSelection (CalypsoSelector cardSelector, boolean acceptInvalidatedCard)
        ..
        +CalypsoSamResourceProfileExtension createSamResourceProfileExtension ()
        +CardTransactionService createCardTransaction (<back:yellow>CardReader</back> reader, CalypsoCard calypsoCard, CardSecuritySetting cardSecuritySetting)
        ..
        +CardTransactionService createCardTransactionWithoutSecurity (<back:yellow>CardReader</back> reader, CalypsoCard calypsoCard)
    }


    +interface "<<<back:yellow>CardSelector</back>>>\nCalypsoSelector" as CalypsoSelector {
        --
        +CalypsoSelector filterByCardProtocol (String cardProtocol)
        +CalypsoSelector filterByPowerOnData (String powerOnDataRegex)
        +CalypsoSelector filterByDfName (byte[] aid)
        +CalypsoSelector filterByDfName (String aid)
        +CalypsoSelector setFileOccurrence (<back:yellow>FileOccurrence</back> fileOccurrence)
        +CalypsoSelector setFileControlInformation (<back:yellow>FileControlInformation</back> fileControlInformation)
        +CalypsoSelector addSuccessfulStatusWord (int statusWord)
        .. **CardSelector** ..
        +String getCardProtocol ()
        +String getPowerOnDataRegex ()
        +byte[] getAid ()
        +<back:yellow>FileOccurrence</back> getFileOccurrence ()
        +<back:yellow>FileControlInformation</back> getFileControlInformation ()
        +Set<Integer> getSuccessfulSelectionStatusWords ()
        +CalypsoSelector addSuccessfulStatusWord (int statusWord)
        +boolean powerOnDataMatches (byte[] powerOnData)
    }

    package card {
        +interface "<<<back:yellow>CardSelection</back>>>\nCalypsoCardSelection" as CalypsoCardSelection {
            --
            ...
        }
        +enum SelectFileControl {
            --
            ...
        }
        +interface "<<<back:yellow>SmartCard</back>>>\nCalypsoCard" as CalypsoCard {
            --
            ...
        }
        +interface DirectoryHeader {
            --
            ...
        }
        +interface ElementaryFile {
            --
            ...
        }
        +interface FileHeader {
            --
            ...
        }
        +interface FileData {
            --
            ...
        }
        +enum CardRevision {
            --
            ...
        }
        +interface SvLoadLogRecord {
            --
            ...
        }
        +interface SvDebitLogRecord {
            --
            ...
        }
    }
    package sam {
        +interface "<<<back:cyan>KeypleCardResourceProfileExtension</back>>>\nCalypsoSamResourceProfileExtension" as CalypsoSamResourceProfileExtension {
            +CalypsoSamResourceProfileExtension setSamRevision (SamRevision samRevision)
            +CalypsoSamResourceProfileExtension setSamSerialNumberRegex (String samSerialNumberRegex)
            +CalypsoSamResourceProfileExtension setSamUnlockData (String samUnlockData)
        }
        +interface "<<<back:yellow>SmartCard</back>>>\nCalypsoSam" as CalypsoSam {
            --
            ...
        }
        +enum SamRevision {
            --
            ...
        }
    }
    package transaction {
        +interface CardTransactionService {
            --
            ...
        }
        +class "**final** CardSecuritySetting" as CardSecuritySetting {
            --
            +{static} Builder builder ()
            ..
            ...
        }
        +class "**final** Builder" as CardSecuritySettingBuilder {
            --
            ...
            +CardSecuritySetting build ()
        }
    }
}

' Associations

CalypsoExtensionService .up.> CalypsoSamResourceProfileExtension #C_USE : create >
CalypsoExtensionService ..> CardSecuritySetting #C_USE : use >
CalypsoExtensionService ..> CalypsoCardSelection #C_USE : create >
CalypsoExtensionService .up.> CalypsoSelector #C_USE : create >
CalypsoExtensionService ..> CalypsoCard #C_USE : use >
CalypsoExtensionService ..> CardTransactionService #C_USE : create >

CardTransactionService ..> CardSecuritySetting #C_USE : use >
CardTransactionService ..> SelectFileControl #C_USE : use >

CardSecuritySetting ..> CardSecuritySettingBuilder #C_USE : provide >

CardSecuritySettingBuilder .up.> CardSecuritySetting #C_USE : create >

CalypsoSamResourceProfileExtension ..> SamRevision #C_USE : use >

CalypsoSam ..> SamRevision #C_USE : provide >

CalypsoCardSelection ..> SelectFileControl #C_USE : use >

CalypsoCard ..> DirectoryHeader #C_USE : provide >
CalypsoCard ..> ElementaryFile #C_USE : provide >
CalypsoCard ..> FileHeader #C_USE : provide >
CalypsoCard ..> FileData #C_USE : provide >
CalypsoCard ..> CardRevision #C_USE : provide >
CalypsoCard ..> SvLoadLogRecord #C_USE : provide >
CalypsoCard ..> SvDebitLogRecord #C_USE : provide >

' == LAYOUT ==

'CardRevision -[hidden]- SamCardResourceServiceBuilder

' == STYLE ==

package calypso #C_GREY1 {}
package card #C_GREY2 {}
package sam #C_GREY2 {}
package transaction #C_GREY2 {}


@enduml