@startuml
title
    Keyple 2.0 - Calypso Card Extension - 2.0.0 (02/06/2021)
end title

' == THEME ==

'Couleurs issues de : https://htmlcolorcodes.com/fr/tableau-de-couleur/tableau-de-couleur-design-plat/
!define C_GREY1 F8F9F9
!define C_GREY2 F2F3F4
!define C_GREY3 E5E7E9
!define C_GREY4 D7DBDD
!define C_GREY5 CACFD2
!define C_GREY6 BDC3C7
!define C_LINK 3498DB
!define C_USE 27AE60

skinparam Shadowing false
skinparam ClassFontStyle italic
skinparam ClassBorderColor #D4AC0D
skinparam stereotypeABorderColor #A9DCDF
skinparam stereotypeIBorderColor #B4A7E5
skinparam stereotypeCBorderColor #ADD1B2
skinparam stereotypeEBorderColor #EB93DF
' Red
skinparam ClassBackgroundColor<<red>> #FDEDEC
skinparam ClassBorderColor<<red>> #E74C3C
hide <<red>> stereotype
' Purple
skinparam ClassBackgroundColor<<purple>> #F4ECF7
skinparam ClassBorderColor<<purple>> #8E44AD
hide <<purple>> stereotype
' blue
skinparam ClassBackgroundColor<<blue>> #EBF5FB
skinparam ClassBorderColor<<blue>> #3498DB
hide <<blue>> stereotype
' Green
skinparam ClassBackgroundColor<<green>> #E9F7EF
skinparam ClassBorderColor<<green>> #27AE60
hide <<green>> stereotype
' Grey
skinparam ClassBackgroundColor<<grey>> #EAECEE
skinparam ClassBorderColor<<grey>> #2C3E50
hide <<grey>> stereotype

' == CONTENT ==

legend top
    __Colors legend__ :
    * __External API references__ :
    ** <back:yellow>**calypsonet-terminal-reader-java-api**</back>
    ** <back:pink>**calypsonet-terminal-calypso-java-api**</back>
    ** <back:cyan>**keyple-java-commons-api**</back>
end legend

package "org.eclipse.keyple.card.calypso" as calypso {
    +class "<<<back:cyan>KeypleCardExtension</back>>>\n**final** CalypsoExtensionService" as CalypsoExtensionService {
        --
        +{static} CalypsoExtensionService getInstance ()
        ..
        +CalypsoSelector createCardSelector ()
        +<back:pink>CalypsoCardSelection</back> createCardSelection (CalypsoSelector cardSelector, boolean acceptInvalidatedCard)
        ..
        +CalypsoSamResourceProfileExtension createSamResourceProfileExtension ()
        +CalypsoCardSecuritySetting createCardSecuritySetting (<back:yellow>CardReader</back> samReader, <back:pink>CalypsoSam</back> calypsoSam)
        +<back:pink>CardTransactionService</back> createCardTransaction (<back:yellow>CardReader</back> cardReader, <back:pink>CalypsoCard</back> calypsoCard, <back:pink>CardSecuritySetting</back> cardSecuritySetting)
        ..
        +<back:pink>CardTransactionService</back> createCardTransactionWithoutSecurity (<back:yellow>CardReader</back> cardReader, <back:pink>CalypsoCard</back> calypsoCard)
    }


    +interface "<<<back:yellow>CardSelector</back>>>\nCalypsoSelector" as CalypsoSelector {
        --
        +CalypsoSelector filterByCardProtocol (String cardProtocol)
        +CalypsoSelector filterByPowerOnData (String powerOnDataRegex)
        +CalypsoSelector filterByDfName (byte[] aid)
        +CalypsoSelector filterByDfName (String aid)
        +CalypsoSelector setFileOccurrence (<back:yellow>FileOccurrence</back> fileOccurrence)
        +CalypsoSelector setFileControlInformation (<back:yellow>FileControlInformation</back> fileControlInformation)
        +CalypsoSelector addSuccessfulStatusWord (int statusWord)
        .. **CardSelector** ..
        +String getCardProtocol ()
        +String getPowerOnDataRegex ()
        +byte[] getAid ()
        +<back:yellow>FileOccurrence</back> getFileOccurrence ()
        +<back:yellow>FileControlInformation</back> getFileControlInformation ()
        +Set<Integer> getSuccessfulSelectionStatusWords ()
        +CalypsoSelector addSuccessfulStatusWord (int statusWord)
        +boolean powerOnDataMatches (byte[] powerOnData)
    }

    +interface "<<<back:cyan>KeypleCardResourceProfileExtension</back>>>\nCalypsoSamResourceProfileExtension" as CalypsoSamResourceProfileExtension {
        +CalypsoSamResourceProfileExtension setSamRevision (<back:pink>CalypsoSam.Revision</back> samRevision)
        +CalypsoSamResourceProfileExtension setSamSerialNumberRegex (String samSerialNumberRegex)
        +CalypsoSamResourceProfileExtension setSamUnlockData (String samUnlockData)
    }

    +interface "<<<back:pink>CardSecuritySetting</back>>>\nCalypsoCardSecuritySetting" as CalypsoCardSecuritySetting {
        --
        +CalypsoCardSecuritySetting enableMultipleSession ()
        +CalypsoCardSecuritySetting enableRatificationMechanism ()
        +CalypsoCardSecuritySetting disablePinEncryption ()
        +CalypsoCardSecuritySetting assignKif (<back:pink>SessionAccessLevel</back> sessionAccessLevel, byte kif)
        +CalypsoCardSecuritySetting assignKvc (<back:pink>SessionAccessLevel</back> sessionAccessLevel, byte kvc)
        +CalypsoCardSecuritySetting assignKeyRecordNumber (<back:pink>SessionAccessLevel</back> sessionAccessLevel, byte keyRecordNumber)
        +CalypsoCardSecuritySetting sessionAuthorizedKvcList (List<Byte> sessionAuthorizedKvcList)
        +CalypsoCardSecuritySetting pinCipheringKey (byte kif, byte kvc)
        +CalypsoCardSecuritySetting isLoadAndDebitSvLogRequired (boolean isLoadAndDebitSvLogRequired)
        +CalypsoCardSecuritySetting isSvNegativeBalanceAllowed (boolean isSvNegativeBalanceAllowed)
        .. **CardSecuritySetting** ..
        +<back:yellow>CardReader</back> getSamReader ()
        +<back:pink>CalypsoSam</back> getCalypsoSam ()
        +boolean isMultipleSessionEnabled ()
        +boolean isRatificationMechanismEnabled ()
        +boolean isPinTransmissionEncryptionDisabled ()
        +Byte getKif (<back:pink>SessionAccessLevel</back> sessionAccessLevel)
        +Byte getKvc (<back:pink>SessionAccessLevel</back> sessionAccessLevel)
        +Byte getKeyRecordNumber (<back:pink>SessionAccessLevel</back> sessionAccessLevel)
        +boolean isKvcAuthorized (byte kvc)
        +byte getPinCipheringKif ()
        +byte getPinCipheringKvc ()
        +boolean isLoadAndDebitSvLogRequired ()
        +boolean isSvNegativeBalanceAllowed ()
    }
}

' Associations

CalypsoExtensionService ..> CalypsoSamResourceProfileExtension #C_USE : create >
CalypsoExtensionService ..> CalypsoCardSecuritySetting #C_USE : create >
CalypsoExtensionService ..> CalypsoSelector #C_USE : create >

' == LAYOUT ==

'CardRevision -[hidden]- SamCardResourceServiceBuilder

' == STYLE ==

package calypso #C_GREY1 {}


@enduml