@startuml
title
    Keyple 2.0 - keyple-java-service - 2.0.0 (21/05/2021)
end title

' == THEME ==

'Couleurs issues de : https://htmlcolorcodes.com/fr/tableau-de-couleur/tableau-de-couleur-design-plat/
!define C_GREY1 F8F9F9
!define C_GREY2 F2F3F4
!define C_GREY3 E5E7E9
!define C_GREY4 D7DBDD
!define C_GREY5 CACFD2
!define C_GREY6 BDC3C7
!define C_LINK 3498DB
!define C_USE 27AE60

skinparam Shadowing false
skinparam ClassFontStyle italic
skinparam ClassBorderColor #D4AC0D
skinparam stereotypeABorderColor #A9DCDF
skinparam stereotypeIBorderColor #B4A7E5
skinparam stereotypeCBorderColor #ADD1B2
skinparam stereotypeEBorderColor #EB93DF
' Red
skinparam ClassBackgroundColor<<red>> #FDEDEC
skinparam ClassBorderColor<<red>> #E74C3C
hide <<red>> stereotype
' Purple
skinparam ClassBackgroundColor<<purple>> #F4ECF7
skinparam ClassBorderColor<<purple>> #8E44AD
hide <<purple>> stereotype
' blue
skinparam ClassBackgroundColor<<blue>> #EBF5FB
skinparam ClassBorderColor<<blue>> #3498DB
hide <<blue>> stereotype
' Green
skinparam ClassBackgroundColor<<green>> #E9F7EF
skinparam ClassBorderColor<<green>> #27AE60
hide <<green>> stereotype
' Grey
skinparam ClassBackgroundColor<<grey>> #EAECEE
skinparam ClassBorderColor<<grey>> #2C3E50
hide <<grey>> stereotype

' == CONTENT ==

legend top
    __Colors legend__ :
    * __External public API references__ :
    ** <back:yellow>**calypsonet-terminal-reader-java-api**</back>
    ** <back:cyan>**keyple-java-commons-api**</back>
end legend

package "org.eclipse.keyple.core.service" as service {
    ' SERVICE

    ' Card Resource Service
    package resource {
        +class "**final** CardResourceServiceProvider" as CardResourceServiceProvider {
            +{static} CardResourceService getService ()
        }

        +interface CardResourceService {
            +CardResourceServiceConfigurator getConfigurator()
            +void start ()
            +void stop ()
            +CardResource getCardResource (String cardResourceProfileName)
            +void releaseCardResource (CardResource cardResource)
            +void removeCardResource (CardResource cardResource)
        }

        +interface CardResourceServiceConfigurator {
            +CardResourceServiceConfigurator withPlugins (PluginsConfigurator pluginsConfigurator)
            +CardResourceServiceConfigurator withPoolPlugins (PoolPluginsConfigurator poolPluginsConfigurator)
            +CardResourceServiceConfigurator withCardResourceProfiles (CardResourceProfileConfigurator... cardResourceProfileConfigurators)
            +CardResourceServiceConfigurator withBlockingAllocationMode (int cycleDurationMillis, int timeoutMillis)
            +void configure ()
        }

        +class "**final** PluginsConfigurator" as PluginsConfigurator {
            +{static} Builder builder ()
        }
        +class "**final** Builder" as PluginsConfiguratorBuilder {
            --
            +Builder withAllocationStrategy (AllocationStrategy allocationStrategy)
            +Builder withUsageTimeout (int usageTimeoutMillis)
            +Builder addPlugin (Plugin plugin, ReaderConfiguratorSpi readerConfiguratorSpi)
            +Builder addPluginWithMonitoring (Plugin plugin, ReaderConfiguratorSpi readerConfiguratorSpi
                \tPluginObservationExceptionHandlerSpi pluginObservationExceptionHandlerSpi,
                \t<back:yellow>CardReaderObservationExceptionHandlerSpi</back> readerObservationExceptionHandlerSpi)
            +PluginsConfigurator build ()
        }
        +enum AllocationStrategy {
            FIRST
            CYCLIC
            RANDOM
        }

        +class "**final** PoolPluginsConfigurator" as PoolPluginsConfigurator {
            +{static} Builder builder ()
        }
        +class "**final** Builder" as PoolPluginsConfiguratorBuilder {
            +Builder usePoolFirst ()
            +Builder addPoolPlugin (PoolPlugin poolPlugin)
            +PoolPluginsConfigurator build ()
        }

        +class "**final** CardResourceProfileConfigurator" as CardResourceProfileConfigurator {
            --
            +{static} Builder builder (String profileName, <back:cyan>KeypleCardResourceProfileExtension</back> cardResourceProfileExtension)
        }
        +class "**final** Builder" as CardResourceProfileConfiguratorBuilder {
            +Builder withPlugins (Plugin... plugins)
            +Builder withReaderNameRegex (String readerNameRegex)
            +Builder withReaderGroupReference (String readerGroupReference)
            +CardResourceProfileConfigurator build ()
        }

        +class "**final** CardResource" as CardResource {
            --
            +CardResource (Reader reader, <back:yellow>SmartCard</back> smartCard)
            ..
            +Reader getReader ()
            +<back:yellow>SmartCard</back> getSmartCard ()
        }

        package "spi" as resourceSpi {
            +interface ReaderConfiguratorSpi {
                +void setupReader (Reader reader)
            }
        }
    }

    together {
        +class "**final** ServiceProperties" as ApiProperties {
            +{static} **final** String VERSION
        }
        ' SELECTION
        +class "**final** CardSelectionServiceFactory" as CardSelectionServiceFactory {
            +{static} <back:yellow>CardSelectionService</back> getService ()
        }
        ' SERVICE
        +class "**final** SmartCardServiceProvider" as SmartCardServiceProvider {
            +{static} SmartCardService getService ()
        }
        +interface SmartCardService {
            --
            +Plugin registerPlugin (<back:cyan>KeyplePluginExtensionFactory</back> pluginFactory)
            +void unregisterPlugin (String pluginName)
            +Set<String> getPluginNames ()
            +Set<Plugin> getPlugins ()
            +Plugin getPlugin (String pluginName)
            ..
            +void checkCardExtension (<back:cyan>KeypleCardExtension</back> cardExtension)
            ..
            +DistributedLocalService registerDistributedLocalService (
                \t<back:cyan>KeypleDistributedLocalServiceExtensionFactory</back> distributedLocalServiceFactory)
            +void unregisterDistributedLocalService (String distributedLocalServiceName)
            +DistributedLocalService getDistributedLocalService (String distributedLocalServiceName)
        }
        +interface Plugin {
            --
            +String getName ()
            +<T extends <back:cyan>KeyplePluginExtension</back>> T getExtension (Class<T> pluginType)
            ..
            +Set<String> getReaderNames ()
            +Set<Reader> getReaders ()
            +Reader getReader (String readerName)
        }
        +interface DistributedLocalService {
            --
            +String getName ()
            +<T extends <back:cyan>KeypleDistributedLocalServiceExtension</back>> T getExtension (
                \tClass<T> distributedLocalServiceType)
        }
        +interface ObservablePlugin extends Plugin {
            --
            +void setEventNotificationExecutorService (
                \tExecutorService eventNotificationExecutorService)
            +void setPluginObservationExceptionHandler (
                \tPluginObservationExceptionHandlerSpi exceptionHandler)
            ..
            +void addObserver (PluginObserverSpi observer)
            +void removeObserver (PluginObserverSpi observer)
            +void clearObservers ()
            +int countObservers ()
        }
        +interface PoolPlugin extends Plugin {
            --
            +SortedSet<String> getReaderGroupReferences ()
            ..
            +Reader allocateReader (String readerGroupReference)
            +void releaseReader (Reader reader)
        }
        +interface "<<<back:yellow>CardReader</back>>>\nReader" as Reader {
            +<T extends <back:cyan>KeypleReaderExtension</back>> T getExtension (Class<T> readerType)
        }
        +interface "<<<back:yellow>ObservableCardReader</back>>>\nObservableReader" as ObservableReader extends Reader {
        }
        ' SPI
        package spi {
            +interface PluginObserverSpi {
                +void onPluginEvent (PluginEvent pluginEvent)
            }
            +interface PluginObservationExceptionHandlerSpi {
                +void onPluginObservationError (String pluginName,
                    \tThrowable e)
            }
        }
    }
    +class "<<<back:yellow>CardReaderEvent</back>>>\n<<<back:cyan>KeypleReaderEvent</back>>>\n**final** ReaderEvent" as ReaderEvent {
        --
        +ReaderEvent (String pluginName, String readerName, <back:yellow>EventType</back> eventType,
            \t<back:yellow>ScheduledCardSelectionsResponse</back> scheduledCardSelectionsResponse)
        ..
        +String getPluginName ()
        .. **CardReaderEvent** ..
        +String getReaderName ()
        +<back:yellow>EventType</back> getEventType ()
        +<back:yellow>ScheduledCardSelectionsResponse</back> getScheduledCardSelectionsResponse ()
    }
    +class "<<<back:cyan>KeyplePluginEvent</back>>>\n**final** PluginEvent" as PluginEvent {
        --
        +PluginEvent (String pluginName, String readerName, EventType eventType)
        +PluginEvent (String pluginName, Set<String> readerNames, EventType eventType)
        ..
        +String getPluginName ()
        +SortedSet<String> getReaderNames ()
        +EventType getEventType ()
    }
    +enum "EventType" as PluginEventType {
        READER_CONNECTED
        READER_DISCONNECTED
        UNREGISTERED
    }
    ' EXCEPTIONS
    +class "<<RuntimeException>>\nKeyplePluginException" as KeyplePluginException {
        +KeyplePluginException (String message)
        +KeyplePluginException (String message, Throwable cause)
    }
}

' Associations
'LocalServiceClient ..> RemoteServiceParameters #C_USE : use >

SmartCardServiceProvider ..> SmartCardService #C_USE : provide >

SmartCardService *-- "0..N" Plugin #C_LINK
SmartCardService *-- "0..N" DistributedLocalService #C_LINK

PluginEvent +-- PluginEventType
PluginEvent *-- "1" PluginEventType #C_LINK

CardResourceServiceProvider ..> CardResourceService #C_USE : provide >

CardResourceService .left.> CardResource #C_USE : provide >
CardResourceService ..> CardResourceServiceConfigurator #C_USE : provide >

CardResource *-- "1" Reader #C_LINK

CardResourceServiceConfigurator ..> CardResourceServiceConfigurator #C_USE
CardResourceServiceConfigurator ..> PluginsConfigurator #C_USE : use >
CardResourceServiceConfigurator ..> PoolPluginsConfigurator #C_USE : use >
CardResourceServiceConfigurator ..> CardResourceProfileConfigurator #C_USE : use >

PluginsConfigurator ..> PluginsConfiguratorBuilder #C_USE : provide >
PluginsConfigurator +-right- AllocationStrategy
PluginsConfigurator *-right- "1" AllocationStrategy #C_LINK

PluginsConfiguratorBuilder ..> PluginsConfiguratorBuilder #C_USE
PluginsConfiguratorBuilder .up.> AllocationStrategy #C_USE : use >
PluginsConfiguratorBuilder ..> ReaderConfiguratorSpi #C_USE : use >
PluginsConfiguratorBuilder .up.> PluginsConfigurator #C_USE : create >

PoolPluginsConfigurator ..> PoolPluginsConfiguratorBuilder #C_USE : provide >

PoolPluginsConfiguratorBuilder ..> PoolPluginsConfiguratorBuilder #C_USE
PoolPluginsConfiguratorBuilder .up.> PoolPluginsConfigurator #C_USE : create >

CardResourceProfileConfigurator ..> CardResourceProfileConfiguratorBuilder #C_USE : provide >

CardResourceProfileConfiguratorBuilder ..> CardResourceProfileConfiguratorBuilder #C_USE
CardResourceProfileConfiguratorBuilder .up.> CardResourceProfileConfigurator #C_USE : create >

Plugin ..> Reader #C_USE : provide >

ObservablePlugin ..> PluginObserverSpi #C_USE : use >
ObservablePlugin ..> PluginObservationExceptionHandlerSpi #C_USE : use >

PluginObserverSpi ..> PluginEvent #C_USE : use >

' == LAYOUT ==

ObservableReader -[hidden]- ReaderEvent
SmartCardServiceProvider -[hidden]right- CardSelectionServiceFactory
ReaderEvent -[hidden]- KeyplePluginException

' == STYLE ==

package service #C_GREY1 {}
package spi #C_GREY2 {}
package resource #C_GREY2 {}
package resourceSpi #C_GREY3 {}

@enduml