@startuml
title
    Keyple 2.0 - keyple-java-distributed-local - 2.0.0 (17/05/2021)
end title

' == THEME ==

'Couleurs issues de : https://htmlcolorcodes.com/fr/tableau-de-couleur/tableau-de-couleur-design-plat/
!define C_GREY1 F8F9F9
!define C_GREY2 F2F3F4
!define C_GREY3 E5E7E9
!define C_GREY4 D7DBDD
!define C_GREY5 CACFD2
!define C_GREY6 BDC3C7
!define C_LINK 3498DB
!define C_USE 27AE60

skinparam Shadowing false
skinparam ClassFontStyle italic
skinparam ClassBorderColor #D4AC0D
skinparam stereotypeABorderColor #A9DCDF
skinparam stereotypeIBorderColor #B4A7E5
skinparam stereotypeCBorderColor #ADD1B2
skinparam stereotypeEBorderColor #EB93DF
' Red
skinparam ClassBackgroundColor<<red>> #FDEDEC
skinparam ClassBorderColor<<red>> #E74C3C
hide <<red>> stereotype
' Purple
skinparam ClassBackgroundColor<<purple>> #F4ECF7
skinparam ClassBorderColor<<purple>> #8E44AD
hide <<purple>> stereotype
' blue
skinparam ClassBackgroundColor<<blue>> #EBF5FB
skinparam ClassBorderColor<<blue>> #3498DB
hide <<blue>> stereotype
' Green
skinparam ClassBackgroundColor<<green>> #E9F7EF
skinparam ClassBorderColor<<green>> #27AE60
hide <<green>> stereotype
' Grey
skinparam ClassBackgroundColor<<grey>> #EAECEE
skinparam ClassBorderColor<<grey>> #2C3E50
hide <<grey>> stereotype

' == CONTENT ==

legend top
    __Colors legend__ :
    * __Configuration modes__ :
    ** <back:lightGreen>**Reader Client Side**</back>
    ** <back:plum>**Reader Server Side**</back>
    ** <back:lightBlue>**Pool Reader Server Side**</back>
    * __External API references__ :
    ** <back:yellow>**Network API**</back>
    ** <back:cyan>**Commons API**</back>
end legend

package "org.eclipse.keyple.distributed" as root {

    +interface "<<<back:cyan>KeypleDistributedLocalServiceExtension</back>>>\nLocalServiceClient" as LocalServiceClient {
        --
        +<back:yellow>AsyncNodeClient</back> getAsyncNode ()
        ..
        +<T> T executeRemoteService (
            \tRemoteServiceParameters parameters,
            \tClass<T> classOfUserOutputData)
    }
    +class "**final** RemoteServiceParameters" as RemoteServiceParameters {
        +{static} Builder builder (String serviceId, String localReaderName)
    }
    +class "**final** Builder" as RemoteServiceParametersBuilder {
        +Builder withUserInputData (Object userInputData)
        +Builder withInitialCardContent (<back:cyan>KeypleSmartCard</back> initialCardContent)
        +RemoteServiceParameters build ()
    }

    +interface "<<<back:cyan>KeypleDistributedLocalServiceExtension</back>>>\nLocalServiceServer" as LocalServiceServer {
        +<back:yellow>SyncNodeServer</back> getSyncNode ()
        +<back:yellow>AsyncNodeServer</back> getAsyncNode ()
    }

    ' Factories
    together {
        +interface "<<<back:cyan>KeypleDistributedLocalServiceExtensionFactory</back>>>\nLocalServiceClientFactory" as LocalServiceClientFactory {
        }
        +interface "<<<back:cyan>KeypleDistributedLocalServiceExtensionFactory</back>>>\nLocalServiceServerFactory" as LocalServiceServerFactory {
        }
    }

    ' Factories builders
    together {
        +class "**final** LocalServiceClientFactoryBuilder" as LocalServiceClientFactoryBuilder {
            + {static} NodeStep builder (String localServiceName)
        }
        +interface "NodeStep" as LocalServiceClientFactoryNodeStep {
            + ReaderStep withSyncNode (<back:yellow>SyncEndpointClientSpi</back> endpoint)
            + ReaderStep withAsyncNode (<back:yellow>AsyncEndpointClientSpi</back> endpoint, int timeoutSeconds)
        }
        +interface "ReaderStep" as LocalServiceClientFactoryReaderStep {
                + BuilderStep withReaderObservation (ReaderEventFilterSpi filter)
            + BuilderStep withoutReaderObservation ()
        }
        +interface "BuilderStep" as LocalServiceClientFactoryBuilderStep {
            + LocalServiceClientFactory build ()
        }

        package spi {
            +interface ReaderEventFilterSpi {
                +Object beforeEventBroadcast (<back:cyan>KeypleReaderEvent</back> event)
                +Class<?> getUserOutputDataClass ()
                +void afterEventBroadcast (Object userOutputData)
                +boolean onEventBroadcastError (RuntimeException exception)
            }
        }
        +class "<<Exception>>\n**final** CancelEventBroadcastException" as CancelEventBroadcastException {
            +CancelEventBroadcastException (String message)
        }

        +class "**final** LocalServiceServerFactoryBuilder" as LocalServiceServerFactoryBuilder {
            + {static} NodeStep builder (String localServiceName)
        }
        +interface "NodeStep" as LocalServiceServerFactoryNodeStep {
            + BuilderStep withSyncNode ()
            + BuilderStep withAsyncNode (<back:yellow>AsyncEndpointServerSpi</back> endpoint)
        }
        +interface "BuilderStep" as LocalServiceServerFactoryBuilderStep {
            + BuilderStep withPoolPlugins (String... poolPluginNames)
            + LocalServiceServerFactory build ()
        }
    }
}

' Associations
LocalServiceClient ..> RemoteServiceParameters #C_USE : use >
RemoteServiceParameters ..> RemoteServiceParametersBuilder #C_USE : provide >
RemoteServiceParametersBuilder .up.> RemoteServiceParameters #C_USE : create >

LocalServiceClientFactoryBuilder ..> LocalServiceClientFactoryNodeStep #C_USE : provide >
LocalServiceClientFactoryNodeStep ..> LocalServiceClientFactoryReaderStep #C_USE
LocalServiceClientFactoryReaderStep ..> LocalServiceClientFactoryBuilderStep #C_USE
LocalServiceClientFactoryReaderStep ..> ReaderEventFilterSpi #C_USE : use >
ReaderEventFilterSpi ..> CancelEventBroadcastException #C_USE : throw >
LocalServiceClientFactoryBuilderStep ..> LocalServiceClientFactory #C_USE : create >
LocalServiceClientFactory ..> LocalServiceClient #C_USE : create >

LocalServiceServerFactoryBuilder ..> LocalServiceServerFactoryNodeStep #C_USE : provide >
LocalServiceServerFactoryNodeStep ..> LocalServiceServerFactoryBuilderStep #C_USE
LocalServiceServerFactoryBuilderStep ..> LocalServiceServerFactoryBuilderStep #C_USE
LocalServiceServerFactoryBuilderStep ..> LocalServiceServerFactory #C_USE : create >
LocalServiceServerFactory ..> LocalServiceServer #C_USE : create >

' == LAYOUT ==

CancelEventBroadcastException -[hidden]- LocalServiceClientFactory

' == STYLE ==

package root #C_GREY1 {}
package spi #C_GREY2 {}

interface LocalServiceClient <<green>>
interface LocalServiceClientFactory <<green>>
class LocalServiceClientFactoryBuilder <<green>>
interface LocalServiceClientFactoryNodeStep <<green>>
interface LocalServiceClientFactoryReaderStep <<green>>
interface LocalServiceClientFactoryBuilderStep <<green>>
class RemoteServiceParameters <<green>>
class RemoteServiceParametersBuilder <<green>>
interface ReaderEventFilterSpi <<green>>
class CancelEventBroadcastException <<green>>

interface LocalServiceServer <<purple>>
interface LocalServiceServerFactory <<purple>>
class LocalServiceServerFactoryBuilder <<purple>>
interface LocalServiceServerFactoryNodeStep <<purple>>
interface LocalServiceServerFactoryBuilderStep <<purple>>

@enduml